### ISSUE TITLE
Watch out for multithreaded servers

### ISSUE THREAD

**Issue by al2o3cr** [audibleblink/sql-trainer#1]
[This code](https://github.com/audibleblink/sql-trainer/blob/master/lib/attempt.rb#L3) causes a nasty bug on multithreaded servers like Puma. The connection is captured at server boot time and shared amongst all the threads. Occasionally two threads try to use the connection simultaneously, which causes everything from crashes to thread hangs - which used to make the app tip over every 3rd Monday.

The fix is to reference `ActiveRecord::Base.connection` instead of `DB` in `results_for`.

**Comment by audibleblink** [comment]
Thanks!
